### ISSUE TITLE
PlantGL no display scene

### ISSUE THREAD

**Issue by mlabadie** [openalea-incubator/oawidgets#16]
I used PlantGL from oawidgets in my package "openalea.strawberry". 

When i used PlantGL scene not display, i test PlantGL with simple example the result is same eg:
``` 
from oawidgets.plantgl import PlantGL
import openalea.plantgl.all as pgl 
scene=pgl.Sphere()
scene
```
ÒUT of scene object:
```
<openalea.plantgl.scenegraph._pglsg.Sphere at 0x25ef4929720>
```
Then i test to plot the scene with PlantGL but nothing is display in vscode or jupyter notebook:
```
PlantGL(scene, group_by_color=False)
```

**Comment by pradal** [comment]
Use %gui qt5 in a shell.
Otherlse, it seems blocking on Windows (it has always been on Linux and Mac)

**Comment by pradal** [comment]
If it works, can you close the issue?
