### ISSUE TITLE
debug group_meshes_by_color() when geometry is a surface

### ISSUE THREAD

**Issue by RamiALBASHA** [openalea-incubator/oawidgets#22]
when a scene object is a surface, group_meshes_by_color() generates the following error :

> local variable 'meshes_crv' referenced before assignment

This happens when the scene is composed of objects with surfaces, not curves :
https://github.com/openalea-incubator/oawidgets/blob/f3d2c50f51985a89cb4fdd1a365b6a9d9a53e196/src/oawidgets/plantgl.py#L158.

A work around is to replace:

    if curves:
        meshes_crv = [curve2mesh([obj]) for obj in list(curves.values())[0]]
    meshes_scene = [scene2mesh(objects)[0] for objects in group_color.values()]
    meshes_scene.extend(meshes_crv)

by:

    meshes_scene = [scene2mesh(objects)[0] for objects in group_color.values()]
    if curves:
        meshes_scene.extend([curve2mesh([obj]) for obj in list(curves.values())[0]])

**Comment by pradal** [comment]
Thanks!
Could you provide a PR?
This would be great!

**Comment by RamiALBASHA** [comment]
I have created a local branch for the modifications but cannot push my branch due to access issues :
> Permission to openalea-incubator/oawidgets.git denied to RamiALBASHA
Could you give me access?
Thanks

**Comment by pradal** [comment]
You  normally have received an invitation

**Comment by RamiALBASHA** [comment]
there you go!
